import { NextResponse } from "next/server";
import { z } from "zod";
import { authenticatedHousehold } from "@/lib/server-auth";
import { createClient } from "@/lib/supabase/server";

const schema = z.object({ kind: z.enum(["planned", "recurring"]), name: z.string().trim().min(1).max(120).optional(), date: z.iso.date().optional(), amountCents: z.number().int().positive().optional(), state: z.enum(["confirmed", "matched", "skipped", "inactive"]).optional(), matchedTransactionId: z.string().uuid().nullable().optional() });
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const auth = await authenticatedHousehold(); if (!auth) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const { id } = await params; const body = schema.safeParse(await request.json()); if (!body.success || !z.string().uuid().safeParse(id).success) return NextResponse.json({ message: "Invalid Plan update." }, { status: 400 });
  const supabase = await createClient(); const value = body.data; const table = value.kind === "planned" ? "planned_items" : "recurring_items";
  if (value.matchedTransactionId) { const { data: transaction } = await supabase.from("transactions").select("id").eq("id", value.matchedTransactionId).eq("household_id", auth.householdId).maybeSingle(); if (!transaction) return NextResponse.json({ message: "Choose a household transaction." }, { status: 400 }); }
  const updates: Record<string, unknown> = { updated_at: new Date().toISOString() }; if (value.name) updates.name = value.name; if (value.amountCents) updates.amount_cents = value.amountCents; if (value.date) updates[value.kind === "planned" ? "date" : "next_due_date"] = value.date; if (value.state) { updates.state = value.state; if (value.kind === "recurring") { updates.active = value.state !== "inactive"; updates.is_confirmed = value.state === "confirmed" || value.state === "matched"; } } if (value.matchedTransactionId !== undefined) updates.matched_transaction_id = value.matchedTransactionId;
  const { error } = await supabase.from(table).update(updates).eq("id", id).eq("household_id", auth.householdId); if (!error) await supabase.from("audit_events").insert({ household_id: auth.householdId, actor_user_id: auth.userId, entity_type: value.kind === "planned" ? "planned_item" : "recurring_item", entity_id: id, action: value.state ?? "edited", metadata: value });
  return NextResponse.json({ message: error ? "Plan item could not be updated." : "Plan item updated." }, { status: error ? 500 : 200 });
}
export async function DELETE(request: Request, { params }: { params: Promise<{ id: string }> }) { const auth = await authenticatedHousehold(); if (!auth) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const { id } = await params; const kind = new URL(request.url).searchParams.get("kind"); if (!z.string().uuid().safeParse(id).success || !["planned","recurring"].includes(kind ?? "")) return NextResponse.json({ message: "Invalid Plan item." }, { status: 400 }); const supabase = await createClient(); const { error } = kind === "planned" ? await supabase.from("planned_items").delete().eq("id", id).eq("household_id", auth.householdId) : await supabase.from("recurring_items").update({ active: false, state: "inactive", updated_at: new Date().toISOString() }).eq("id", id).eq("household_id", auth.householdId); return NextResponse.json({ message: error ? "Plan item could not be removed." : "Plan item removed." }, { status: error ? 500 : 200 }); }
