"use client";

import { Plus, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { ExpectedIncomeSource } from "@/lib/data";
import { formatCurrency } from "@/lib/utils";

export function ExpectedIncomeSettings({ initialSources }: { initialSources: ExpectedIncomeSource[] }) {
  const router = useRouter(); const [sources, setSources] = useState(initialSources); const [message, setMessage] = useState(""); const [adding, setAdding] = useState(false);
  async function save(source: ExpectedIncomeSource, isNew = false) {
    const response = await fetch(isNew ? "/api/income-sources" : `/api/income-sources/${source.id}`, { method: isNew ? "POST" : "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(source) });
    const body = await response.json() as { message?: string; id?: string }; setMessage(body.message ?? "");
    if (response.ok) { if (isNew) setSources([...sources, { ...source, id: body.id ?? source.id }]); else setSources(sources.map((item) => item.id === source.id ? source : item)); setAdding(false); router.refresh(); } return response.ok;
  }
  async function remove(id: string) { const response = await fetch(`/api/income-sources/${id}`, { method: "DELETE" }); const body = await response.json() as { message?: string }; setMessage(body.message ?? ""); if (response.ok) { setSources(sources.filter((item) => item.id !== id)); router.refresh(); } }
  const blank: ExpectedIncomeSource = { id: "new", name: "", expectedAmountCents: 0, cadence: "monthly", nextExpectedDate: "", explicitDates: [], active: true, sourceType: "recurring", acceptableVarianceCents: null };
  return <details className="settings-disclosure card expected-income-settings" open={adding || undefined}><summary><span>$</span><span><strong>Expected income</strong><small>{sources.filter((item) => item.active).length} active · household-managed schedule</small></span><button type="button" className="group-icon-button" aria-label="Add expected income" onClick={(event) => { event.preventDefault(); setAdding(true); }}><Plus size={17} /></button></summary><div className="expected-income-list">{sources.map((source) => <IncomeSourceEditor key={source.id} source={source} onDelete={() => remove(source.id)} onSave={(value) => save(value)} />)}{adding ? <IncomeSourceEditor source={blank} onDelete={() => setAdding(false)} onSave={(value) => save(value, true)} /> : null}{!sources.length && !adding ? <p className="compact-empty">Add paychecks or one-time income so Budget can calculate Left to assign.</p> : null}<p className="form-message" role="status">{message}</p></div></details>;
}

function IncomeSourceEditor({ source, onDelete, onSave }: { source: ExpectedIncomeSource; onDelete: () => void; onSave: (source: ExpectedIncomeSource) => Promise<boolean> }) {
  const [draft, setDraft] = useState(source); const [editing, setEditing] = useState(source.id === "new");
  if (!editing) return <div className="expected-income-row"><div><strong>{draft.name}</strong><span>{formatCurrency(draft.expectedAmountCents)} · {draft.sourceType === "one_time" ? "one time" : draft.cadence} · {draft.nextExpectedDate || "explicit dates"}{draft.active ? "" : " · inactive"}</span></div><button className="secondary-button compact-button" onClick={() => setEditing(true)}>Edit</button></div>;
  return <div className="expected-income-editor"><div className="field"><label>Name</label><input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></div><div className="expected-income-grid"><div className="field"><label>Amount</label><input type="number" min="0.01" step="0.01" value={draft.expectedAmountCents ? draft.expectedAmountCents / 100 : ""} onChange={(event) => setDraft({ ...draft, expectedAmountCents: Math.round(Number(event.target.value) * 100) })} /></div><div className="field"><label>Type</label><select value={draft.sourceType} onChange={(event) => setDraft({ ...draft, sourceType: event.target.value as ExpectedIncomeSource["sourceType"] })}><option value="recurring">Recurring</option><option value="one_time">One time</option></select></div><div className="field"><label>Next date</label><input type="date" value={draft.nextExpectedDate ?? ""} onChange={(event) => setDraft({ ...draft, nextExpectedDate: event.target.value || null })} /></div>{draft.sourceType === "recurring" ? <div className="field"><label>Cadence</label><select value={draft.cadence ?? "monthly"} onChange={(event) => setDraft({ ...draft, cadence: event.target.value })}><option value="weekly">Weekly</option><option value="biweekly">Every two weeks</option><option value="semimonthly">Twice monthly</option><option value="monthly">Monthly</option><option value="annual">Annual</option></select></div> : null}<div className="field"><label>Acceptable variance</label><input type="number" min="0" step="0.01" placeholder="Exact amount" value={draft.acceptableVarianceCents === null ? "" : draft.acceptableVarianceCents / 100} onChange={(event) => setDraft({ ...draft, acceptableVarianceCents: event.target.value === "" ? null : Math.max(0, Math.round(Number(event.target.value) * 100)) })} /></div></div><label className="account-checkbox"><input type="checkbox" checked={draft.active} onChange={(event) => setDraft({ ...draft, active: event.target.checked })} /> Active</label><div className="expected-income-actions"><button className="primary-button" disabled={!draft.name.trim() || draft.expectedAmountCents <= 0 || !draft.nextExpectedDate} onClick={async () => { if (await onSave(draft)) setEditing(false); }}>Save income</button><button className="text-button danger-text" onClick={onDelete}><Trash2 size={16} /> {source.id === "new" ? "Cancel" : "Delete"}</button></div></div>;
}
