"use client";

import { format } from "date-fns";
import { Check, FileSpreadsheet, Upload, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { ImportInboxItem } from "@/lib/data";

const typeLabels: Record<string, string> = { bank_transactions: "Bank transaction CSV", credit_card_transactions: "Credit-card transaction CSV", budget_template: "Budget template CSV/XLSX", income: "Income or paycheck", recurring_bills: "Recurring bills", planned_expenses: "Planned expenses" };

export function ImportInbox({ initialImports, accounts }: { initialImports: ImportInboxItem[]; accounts: Array<{ id: string; name: string }> }) {
  const router = useRouter(); const [type, setType] = useState("bank_transactions"); const [accountId, setAccountId] = useState(accounts[0]?.id ?? ""); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const needsAccount = type === "bank_transactions" || type === "credit_card_transactions";
  async function upload(event: React.FormEvent) { event.preventDefault(); if (!file) return; setLoading(true); setMessage(""); const data = new FormData(); data.set("file", file); data.set("importType", type); if (needsAccount) data.set("accountId", accountId); const response = await fetch("/api/imports", { method: "POST", body: data }); const body = await response.json() as { message?: string }; setLoading(false); setMessage(body.message ?? ""); if (response.ok) { setFile(null); router.refresh(); } }
  async function action(id: string, actionName: "apply" | "reject") { setLoading(true); const response = await fetch(`/api/imports/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: actionName }) }); const body = await response.json() as { message?: string }; setLoading(false); setMessage(body.message ?? ""); router.refresh(); }
  return <>
    <form className="import-upload card" onSubmit={upload}><div className="import-upload-icon"><Upload /></div><div className="field"><label htmlFor="import-type">Document type</label><select id="import-type" value={type} onChange={(event) => setType(event.target.value)}>{Object.entries(typeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>{needsAccount ? <div className="field"><label htmlFor="import-account">Account</label><select id="import-account" required value={accountId} onChange={(event) => setAccountId(event.target.value)}><option value="">Choose account</option>{accounts.map((account) => <option value={account.id} key={account.id}>{account.name}</option>)}</select></div> : null}<div className="field"><label htmlFor="import-file">CSV, XLSX, or PDF · 10 MB maximum</label><input id="import-file" type="file" accept=".csv,.xlsx,.pdf,text/csv,application/pdf" required onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></div><button className="primary-button" disabled={loading || !file}>{loading ? "Processing…" : "Upload for review"}</button><p className="import-safety">PDF contents are retained for review and never applied automatically.</p></form>
    <p className="form-message" role="status">{message}</p><div className="section-heading"><h2>Import history</h2></div>
    {initialImports.length ? <div className="import-history">{initialImports.map((item) => <details className="import-card card" key={item.id} open={item.status === "review" || item.status === "ready"}><summary><FileSpreadsheet /><span><strong>{item.fileName}</strong><small>{typeLabels[item.importType] ?? item.importType} · {format(new Date(item.createdAt), "MMM d, yyyy")}</small></span><em className={`import-status ${item.status}`}>{item.status}</em></summary><div className="import-counts"><span><strong>{item.acceptedRows}</strong> accepted</span><span><strong>{item.duplicateRows}</strong> duplicate</span><span><strong>{item.reviewRows}</strong> review</span></div>{item.rows.length ? <div className="import-preview">{item.rows.slice(0, 100).map((row) => <ImportRow key={row.id} importId={item.id} row={row} />)}</div> : <p className="import-empty">No structured rows are available. Review the error above or upload a CSV/XLSX version.</p>}<div className="import-actions">{!['applied','rejected','error'].includes(item.status) ? <><button className="primary-button" disabled={loading || item.status !== "ready"} onClick={() => action(item.id, "apply")}><Check size={17} /> Apply accepted rows</button><button className="secondary-button" disabled={loading} onClick={() => action(item.id, "reject")}><X size={17} /> Reject</button></> : null}</div></details>)}</div> : <div className="empty-state card"><FileSpreadsheet /><h2>No imports yet</h2><p>Your uploaded documents and review history will appear here.</p></div>}
  </>;
}

function ImportRow({ importId, row }: { importId: string; row: ImportInboxItem["rows"][number] }) {
  const router = useRouter(); const [editing, setEditing] = useState(false); const [values, setValues] = useState(row.normalized); const [message, setMessage] = useState("");
  async function save() { const response = await fetch(`/api/imports/${importId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "update_row", rowId: row.id, normalized: values }) }); const body = await response.json() as { message?: string }; setMessage(body.message ?? ""); if (response.ok) { setEditing(false); router.refresh(); } }
  return <div className={`import-row ${row.status}`}><div className="import-row-heading"><strong>Row {row.rowNumber}</strong><span>{row.status}</span><button onClick={() => setEditing(!editing)}>{editing ? "Cancel" : "Correct"}</button></div>{editing ? <div className="import-row-fields">{Object.entries(values).map(([key, value]) => <label key={key}><span>{key}</span><input value={typeof value === "number" ? value : String(value ?? "")} type={key.toLowerCase().includes("cents") ? "number" : "text"} onChange={(event) => setValues({ ...values, [key]: key.toLowerCase().includes("cents") ? Number(event.target.value) : event.target.value })} /></label>)}<button className="secondary-button" onClick={save}>Validate row</button></div> : <p>{Object.entries(values).map(([key, value]) => `${key}: ${String(value ?? "—")}`).join(" · ")}</p>}{row.errors.map((error) => <small className="row-error" key={error}>{error}</small>)}<small>{message}</small></div>;
}
