"use client";
import { Check, Pencil, SkipForward, Trash2 } from "lucide-react";
import { format, parseISO } from "date-fns";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { ActivityTransaction } from "@/lib/data";
import { formatCurrency } from "@/lib/utils";

type Item = { id: string; name: string; date: string; amountCents: number; type: "income" | "expense"; state: string; kind: "planned" | "recurring"; matchedTransactionId: string | null };
export function PlanList({ initialItems, transactions }: { initialItems: Item[]; transactions: ActivityTransaction[] }) { const router = useRouter(); const [items,setItems]=useState(initialItems); const [editing,setEditing]=useState<Item|null>(null); const [message,setMessage]=useState(""); async function update(item:Item,payload:Record<string,unknown>){const response=await fetch(`/api/plan/${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({kind:item.kind,...payload})});const body=await response.json() as {message?:string};setMessage(body.message??"");if(response.ok){setItems(items.map((value)=>value.id===item.id?{...value,...payload}:value).filter((value)=>value.state!=="skipped"));setEditing(null);router.refresh();}} async function remove(item:Item){if(!window.confirm(`Remove ${item.name}?`))return;const response=await fetch(`/api/plan/${item.id}?kind=${item.kind}`,{method:"DELETE"});if(response.ok){setItems(item.kind==="recurring"?items.map((value)=>value.id===item.id?{...value,state:"inactive"}:value):items.filter((value)=>value.id!==item.id));router.refresh();}}
return <><section className="card plan-timeline">{items.length?items.map((item)=><div className={`plan-item ${item.type}`} key={item.id}><div className="plan-meta"><strong>{item.name}</strong><span>{format(parseISO(item.date),"EEEE, MMM d")} · {item.state}</span></div><strong>{formatCurrency(item.type==="income"?item.amountCents:-item.amountCents,{signed:true})}</strong><div className="plan-item-actions"><button aria-label={`Edit ${item.name}`} onClick={()=>setEditing(item)}><Pencil size={15}/></button>{item.state==="inactive"?<button aria-label={`Activate ${item.name}`} onClick={()=>void update(item,{state:"confirmed"})}><Check size={15}/></button>:<><button aria-label={`Skip ${item.name}`} onClick={()=>void update(item,{state:item.kind==="recurring"?"inactive":"skipped"})}><SkipForward size={15}/></button><button aria-label={`Match ${item.name}`} onClick={()=>setEditing({...item,state:"matched"})}><Check size={15}/></button></>}<button aria-label={`Remove ${item.name}`} onClick={()=>void remove(item)}><Trash2 size={15}/></button></div></div>):<p className="plan-empty">Nothing planned yet.</p>}</section>{editing?<div className="card plan-inline-edit"><div className="field"><label>Name</label><input value={editing.name} onChange={(event)=>setEditing({...editing,name:event.target.value})}/></div><div className="field"><label>Date</label><input type="date" value={editing.date} onChange={(event)=>setEditing({...editing,date:event.target.value})}/></div><div className="field"><label>Amount</label><input type="number" value={editing.amountCents/100} onChange={(event)=>setEditing({...editing,amountCents:Math.round(Number(event.target.value)*100)})}/></div>{editing.state==="matched"?<div className="field"><label>Matching transaction</label><select value={editing.matchedTransactionId??""} onChange={(event)=>setEditing({...editing,matchedTransactionId:event.target.value||null})}><option value="">Choose transaction</option>{transactions.filter((transaction)=>Math.sign(transaction.amountCents)===(editing.type==="income"?1:-1)).map((transaction)=><option value={transaction.id} key={transaction.id}>{transaction.merchant} · {formatCurrency(transaction.amountCents,{signed:true})}</option>)}</select></div>:null}<button className="primary-button" disabled={editing.state==="matched"&&!editing.matchedTransactionId} onClick={()=>void update(editing,{name:editing.name,date:editing.date,amountCents:editing.amountCents,state:editing.state,matchedTransactionId:editing.matchedTransactionId})}>{editing.state==="matched"?"Match transaction":"Save changes"}</button></div>:null}<p className="form-message">{message}</p></>}
